# **Pytorch Tutorial**


In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [2]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-0.7739, -0.5273, -0.6627, -2.3531,  0.4345],
        [-1.1546,  0.4042,  0.5876,  1.6503,  0.2581],
        [ 0.3521,  0.4189, -0.1243, -0.7088, -1.2022],
        [ 0.7384, -0.7036,  1.6616, -1.5933, -0.8553]])
tensor([[-1.3002, -0.1374, -0.9435, -0.0197,  0.6155],
        [ 0.9696, -0.2679, -1.5614,  0.2913, -1.0361],
        [ 0.6776,  0.8934, -1.1172,  1.3839,  0.1024],
        [-1.2619, -1.0527,  1.1889,  0.3001, -0.4432]])
tensor([[-0.8736,  0.4311, -0.6064,  0.4901,  0.2984],
        [ 0.1861, -0.0986, -1.5059, -0.4095,  1.7664],
        [ 0.2681, -0.0733, -0.4028,  0.2962,  0.8948],
        [-1.1578,  1.1412, -0.1512,  1.0297, -0.4555]])


In [ ]:
print(torch.zeros(2,3, dtype=torch.int64))

tensor([[0, 0, 0],
        [0, 0, 0]])


In [9]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)
# max = x[0][0]
# for row in x:
#     for col in row:
#         if col>max:
#             max = col

tensor(1.6616)


In [10]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([0.7384, 0.4189, 1.6616, 1.6503, 0.4345])
tensor([3, 2, 3, 1, 0])


In [11]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.7384, 0.4189, 1.6616, 1.6503, 0.4345])
tensor([3, 2, 3, 1, 0])


In [22]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([0.7384, 0.4189, 1.6616, 1.6503, 0.4345])
tensor([3, 2, 3, 1, 0])


In [53]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[0.7384, 0.4189, 1.6616, 1.6503, 0.4345]])
tensor([[3, 2, 3, 1, 0]])


In [56]:
# 2-5
dim_m = torch.Tensor.dim(m)
dim_idx = torch.Tensor.dim(idx)
if dim_m>=2:
    for i in range(dim_m-1):
        m = m[0]
if dim_idx>=2:
    for i in range(dim_idx-1):
        idx = idx[0]
p = (m, idx)
# p = (m[0],idx[0]) # 2-4的例子中m与idx维数进行调整来应对torch.max的输出 m[0] idx[0]
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.7384, 0.4189, 1.6616, 1.6503, 0.4345])
tensor([3, 2, 3, 1, 0])


In [52]:
# 2-6 错误示范，因为顺序原因out=p必须指定参数名
p = (m,idx)
torch.max(x,0,False,p)

TypeError: max() received an invalid combination of arguments - got (Tensor, int, bool, tuple), but expected one of:
 * (Tensor input, *, Tensor out)
 * (Tensor input, Tensor other, *, Tensor out)
      didn't match because some of the arguments have invalid types: (Tensor, !int!, !bool!, !tuple of (Tensor, Tensor)!)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)


In [57]:
# 2-7
m, idx = torch.max(x,True)

TypeError: max() received an invalid combination of arguments - got (Tensor, bool), but expected one of:
 * (Tensor input, *, Tensor out)
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)


In [58]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[-0.7739, -0.1374, -0.6627, -0.0197,  0.6155],
        [ 0.9696,  0.4042,  0.5876,  1.6503,  0.2581],
        [ 0.6776,  0.8934, -0.1243,  1.3839,  0.1024],
        [ 0.7384, -0.7036,  1.6616,  0.3001, -0.4432]])


In [59]:
# tensors should be the same size in torch.max(tensor1, tensor2)
a = torch.randn(3,3)
b = torch.randn(2,2)
c = torch.max(a,b)
print(c)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [60]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

In [61]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [ ]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: ignored

In [64]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [67]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


OutOfMemoryError: CUDA out of memory. Tried to allocate 7.27 GiB (GPU 0; 8.00 GiB total capacity; 1.41 GiB already allocated; 5.52 GiB free; 1.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [68]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [69]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: expected scalar type Long but found Float

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [70]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [71]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [79]:
import torch
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['q']
['z']
['x']
['a']
['j']
['r']
['b']
['g']
['t']
['c']
['l']
['d']
['n']
['o']
['u']
['w']
['m']
['s']
['i']
['h']
['e']
['p']
['f']
['v']
['y']
['k']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [82]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['e']
['F']
['D']
['b']
['I']
['R']
['K']
['d']
['T']
['P']
['N']
['i']
['t']
['Z']
['C']
['B']
['a']
['c']
['G']
['L']
['J']
['Q']
['r']
['o']
['U']
['A']
['l']
['u']
['w']
['m']
['j']
['E']
['x']
['v']
['n']
['f']
['z']
['H']
['M']
['s']
['V']
['X']
['Y']
['h']
['O']
['W']
['S']
['p']
['g']
['q']
['y']
['k']
